
export const CHANGE_SINGER_LIST = 'singer/CHANGE_SINGER_LIST';
export const CHANGE_PAGE_COUNT = 'singer/PAGE_COUNT';
export const CHANGE_ENTER_LOADING = 'singer/ENTER_LOADING';
export const CHANGE_PULLUP_LOADING = 'singer/PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'singer/PULLDOWN_LOADING';
