
export const CHANGE_SINGER_LIST = 'Singer/CHANGE_SINGER_LIST';
export const CHANGE_PAGE_COUNT = 'Singer/PAGE_COUNT';
export const CHANGE_ENTER_LOADING = 'Singer/ENTER_LOADING';
export const CHANGE_PULLUP_LOADING = 'Singer/PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'Singer/PULLDOWN_LOADING';
